# Generated by Django 5.0 on 2024-02-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mentor_department', models.TextField(max_length=20)),
                ('experiences', models.IntegerField(blank=True, null=True)),
                ('mentor_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=15)),
                ('full_name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=40)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_stud', models.CharField(max_length=7)),
                ('program', models.TextField(max_length=100)),
                ('student_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.mentor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.user')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_absent', models.TextField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('total_leave', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('reason', models.TextField(max_length=200)),
                ('proof_pic', models.ImageField(blank=True, null=True, upload_to='proofpic/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('approval_date', models.DateField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.student')),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.user'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('admin_department', models.TextField(max_length=20)),
                ('admin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.user')),
            ],
        ),
    ]
