# Generated by Django 5.0 on 2024-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='proof_pic',
        ),
        migrations.AlterField(
            model_name='application',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
