# Generated by Django 5.0 on 2024-02-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0002_remove_application_proof_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approval_date',
            field=models.DateField(blank=True, default='N/A', null=True),
        ),
    ]
