# Generated by Django 5.0 on 2024-02-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0003_alter_application_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approval_date',
            field=models.DateField(blank=True, default='0000-00-00', null=True),
        ),
    ]
