# Generated by Django 5.0 on 2024-02-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_alter_application_approval_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approval_date',
        ),
    ]
