# Generated by Django 5.0 on 2024-02-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0005_remove_application_approval_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
