# Generated by Django 5.0 on 2024-02-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applications', '0006_remove_application_student_id_remove_mentor_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passwordadmin', models.CharField(default='adminkpmb@2024', max_length=20)),
                ('admin_department', models.TextField(max_length=20)),
                ('admin_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passwordmentor', models.CharField(default='mentorkpmb@2024', max_length=20)),
                ('mentor_department', models.TextField(max_length=20)),
                ('experiences', models.IntegerField(blank=True, null=True)),
                ('mentor_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('passwordstud', models.CharField(default='studentkpmb@2024', max_length=25)),
                ('class_stud', models.CharField(max_length=7)),
                ('program', models.TextField(max_length=100)),
                ('student_number', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_name', models.TextField(max_length=100)),
                ('parent_number', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_adress', models.TextField(max_length=200)),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('total_leave', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('classestobemissed', models.CharField(blank=True, max_length=20, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applications.student')),
            ],
        ),
    ]
