# Generated by Django 5.0 on 2024-02-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor_id',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
